<?php

class Hello extends CI_Controller
{
    /**
     * Index Page for this controller.
     * Maps to the following URL
     * http://example.com/index.php/hello
     * - or -
     * http://example.com/index.php/hello/index
     * - or -
     * since this controller is set as the default controller in the config/routes.php, it's displayed at http://example.com/
     * So any other public methods not prefixed with underscore will map to /index.php/welcome/<method_name>
     * @see http://codeigniter.com/user_guide/general/urls.html
     */
    public function index()
    {
        // Note that $view_params is optional
        // we can use $this->load->view('helloview') as well.
        // if the view doesn't use php variables
        // The $view_params is extracted in the view script to php
        // variable $ key = $value
        // In this example three variables will be generated by CI in the
        // view page
        // helloview.php
        // $mega_title => Codeigniter - Hello World
        // $title => Welcome to Codeigniter
        // $message => Hello World
        $view_params = array(
            'mega_title' => 'Codeigniter - Hello World',
            'title' => 'Welcome to Codeigniter',
            'message' => 'Hello World'
        );
        $this->load->view('helloview', $view_params);
    }
} // Closing the class definition
/* End of file welcome.php */
/* Location: ./application/controller/welcome.php */
